services:
  rss-bridge-youtube:
    image: rss-bridge-youtube:latest
    build: .
    container_name: rss-bridge-youtube
    restart: unless-stopped
    env_file: .env

networks:
  default:
    name: rss-bridge-youtube-network
    driver: bridge
